name: regression-test
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests: 
    name: run-reg-test

    runs-on: windows-latest  #ubuntu-latest

    steps: 
      - name: CheckOut
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 18.14.0
      - uses: microsoft/playwright-github-action@v1
           
      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test createACustomerModule --workers 1 --project chromium --headed
